apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headroom-data
  labels:
    {{- include "headroom.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- with .Values.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
