
# configuration: https://github.com/PacoVK/tapir/blob/main/docs/configuration.md
tapir:
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Service Configuration                                                     │
  # └─────────────────────────────────────────────────────────────────────────────┘
  service:
    type: ClusterIP
    portHttps: 8080

  deployment:
    # ┌─────────────────────────────────────────────────────────────────────────────┐
    # │   Resource Configuration                                                    │
    # └─────────────────────────────────────────────────────────────────────────────┘
    resources:
      requests:
        cpu: 256m
        memory: 256Mi
    configuration:
      # ┌─────────────────────────────────────────────────────────────────────────────┐
      # │   OAuth Configuration                                                     │
      # └─────────────────────────────────────────────────────────────────────────────┘
      auth:
        # Github client creds
        clientId:
        clientSecret:
        # GitHub OIDC endpoints
        endpoint: "https://github.com"
        path: "/login/oauth/authorize"
        tokenPath: "/login/oauth/access_token"
      # ┌─────────────────────────────────────────────────────────────────────────────┐
      # │   Backend Configuration                                                   │
      # └─────────────────────────────────────────────────────────────────────────────┘
      # Supported backends: elasticsearch, dynamodb, cosmosdb (nonsql compatible)
      backend:
        type: "cosmosdb"
        cosmosdb:
          endpoint:
          masterKey:
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Storage Configuration                                                     │
  # └─────────────────────────────────────────────────────────────────────────────┘
      storage:
        # -- Storage type: s3, azureBlob, local
        type: "local"
        # -- Amount of minutes the signed download url is valid
        storageAccessDuration: 5
  persistence:
    enabled: true
    storageClass: "csi-hostpath-sc"
    accessModes: ["ReadWriteOnce"]
    size: "5Gi"
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Autoscaling Configuration                                                │
  # └─────────────────────────────────────────────────────────────────────────────┘
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 75
