apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stackgres-restapi-admin
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-{{ .Values.dopplerConfig | replace "_" "-" }}
  refreshInterval: 1m
  target:
    name: stackgres-restapi-admin
    creationPolicy: Owner
  data:
    - secretKey: k8sUsername
      remoteRef:
        key: ADMIN_USER
    - secretKey: clearPassword
      remoteRef:
        key: ADMIN_PASSWORD
