{{- if .Values.renderClusters }}
{{- range $name, $c := .Values.postgres.clusters }}
apiVersion: stackgres.io/v1
kind: SGPoolingConfig
metadata:
  name: {{ $c.poolingConfigName }}
  namespace: {{ $c.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  pgBouncer:
    pgbouncer.ini:
      pgbouncer:
        pool_mode: transaction
        max_client_conn: "100"
---
{{- end }}
{{- end }}
