{{- if .Values.renderClusters }}
{{- range $name, $c := .Values.postgres.clusters }}
{{- if $c.backups.createStorageAccountSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $c.backups.credentialsSecret }}
  namespace: {{ $c.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-{{ $.Values.dopplerConfig | replace "_" "-" }}
  target:
    name: {{ $c.backups.credentialsSecret }}
    creationPolicy: Owner
  data:
    - secretKey: R2_ACCESS_KEY_ID
      remoteRef:
        key: R2_ACCESS_KEY_ID
    - secretKey: R2_SECRET_ACCESS_KEY
      remoteRef:
        key: R2_SECRET_ACCESS_KEY
---
{{- end }}
{{- end }}
{{- end }}
