dopplerConfig: "svc_cloudflare"

domain: maklab.net
certEmail: admin@maklab.net

cloudflare:
  apiTokenSecretName: cloudflare-api-token
  apiTokenSecretKey: CF_API_TOKEN

gateway:
  name: maklab-gateway
  namespace: istio-system

certificate:
  name: wildcard-maklab-net
  secretName: wildcard-maklab-net-tls
  duration: 2160h
  renewBefore: 720h

