dopplerConfig: "svc_cloudflare"

clusterDomain: maklab.net
certEmail: admin@maklab.net

cloudflare:
  apiTokenSecretName: cloudflare-api-token
  apiTokenSecretKey: CF_API_TOKEN

gateway:
  name: maklab-gateway
  namespace: istio-system

certificate:
  name: wildcard-maklab-net
  secretName: wildcard-maklab-net-tls
  duration: 2160h
  renewBefore: 720h

virtualServices:
  argocd:
    enabled: true
    host: argocd.maklab.net
    destination:
      host: argo-cd-argocd-server.argocd.svc.cluster.local
      port: 80

