apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: {{ .Values.certificate.secretName }}
  duration: {{ .Values.certificate.duration }}
  renewBefore: {{ .Values.certificate.renewBefore }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.{{ .Values.clusterDomain }}"
    - {{ .Values.clusterDomain | quote }}
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
