cloudnative-pg:
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   General Configuration                                                     │
  # └─────────────────────────────────────────────────────────────────────────────┘
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70
