#!/bin/bash
#
# Helm chart lint + dry-run test. Two modes:
#   LOCAL:  ct_check.sh --dir services/helm/<chart>
#   CI:     ct_check.sh "file1.yaml file2.yaml" [lint|install]
#
# An EMPTY CI file list is a valid "nothing to check" input (a PR that touches
# no chart paths), not a usage error: it exits 0 with a skip message.
#
# For umbrella charts with strict subchart schemas, runs with
# --skip-schema-validation on helm template to avoid false failures.

set -euo pipefail

GREEN="\033[32m"
BLUE="\033[34m"
RED="\033[31m"
RESET="\033[0m"
helm_dirs=()
mode="${2:-lint}"

# ── Parse args ──────────────────────────────────────────────────────
if [[ "${1:-}" == "--dir" ]]; then
  # --- Local mode: one chart directory ---
  chart_dir="${2:-}"
  if [[ -z "$chart_dir" ]]; then
    echo -e "${RED}Usage: $0 --dir <chart-directory>${RESET}"
    exit 1
  fi
  helm_dirs=("$chart_dir")
  mode="local"
else
  # --- CI mode: space-separated changed files ---
  # An empty list is a valid no-op, not a usage error: a PR that touches no
  # chart paths yields an empty `all_changed_files`, and failing here blocked
  # every chart-agnostic PR behind branch protection.
  changed_files="${1:-}"
  if [[ -z "$changed_files" ]]; then
    echo "No changed files given; nothing to check. Skipping."
    exit 0
  fi
  IFS=' ' read -r -a files_array <<< "$changed_files"
  for file in "${files_array[@]}"; do
    # Resolve a changed file to its CHART directory by walking up to the nearest
    # ancestor that has a Chart.yaml.
    #
    # Deriving it from a fixed pattern (dirname + sed on `argocd-appset|helm/<one
    # segment>`) only ever worked for files sitting exactly one level below the
    # chart root: a change under apps/helm/templates/ resolved to
    # apps/helm/templates, which is not a chart, and helm then died on a path with
    # no Chart.yaml — failing CI for a correct change. Walking up needs no
    # knowledge of the layout and cannot resolve to a non-chart.
    helm_dir=$(dirname "$file")
    while [[ "$helm_dir" != "." && "$helm_dir" != "/" && ! -f "$helm_dir/Chart.yaml" ]]; do
      helm_dir=$(dirname "$helm_dir")
    done
    [[ -f "$helm_dir/Chart.yaml" ]] || continue
    if [[ ! " ${helm_dirs[@]} " =~ " ${helm_dir} " ]]; then
      helm_dirs+=("$helm_dir")
    fi
  done
fi

# ── No charts found ─────────────────────────────────────────────────
if [[ ${#helm_dirs[@]} -eq 0 ]]; then
  echo "No Helm charts detected in changed files. Skipping."
  exit 0
fi

# ── Resolve deps + lint each chart ──────────────────────────────────
echo -e "${BLUE}Testing ${#helm_dirs[@]} chart(s): ${helm_dirs[*]}${RESET}"

for dir in "${helm_dirs[@]}"; do
  chart_name=$(basename "$dir")
  echo ""
  echo -e "${BLUE}── ${chart_name} ──${RESET}"

  # A chart that cannot render from its own values alone (spec-driven charts
  # render nothing until told WHICH spec, e.g. apps/helm needs appName) declares
  # its CI render inputs in .ci-values.yaml. Without this, `helm template` on such
  # a chart fails with "appName must be set" and every PR touching it fails CI —
  # which is how this was found.
  extra_values=()
  if [[ -f "$dir/.ci-values.yaml" ]]; then
    echo "  → using $dir/.ci-values.yaml"
    extra_values=(-f "$dir/.ci-values.yaml")
  fi

  # Run helm dependency update (pulls OCI charts, links file:// deps)
  if [[ -f "$dir/Chart.yaml" ]]; then
    echo "  → helm dependency update"
    helm dependency update "$dir" > /dev/null 2>&1 || {
      echo -e "${RED}  ✗ helm dependency update failed${RESET}"
      exit 1
    }
    # hermes-agent schema rejects Helm's injected `global` key; patch the
    # fresh tgz so helm lint passes for real (no-op for other charts).
    .useful-scripts/patch_hermes_schema.sh "$dir" >/dev/null
  fi

  # Helm lint (schema + YAML validation; may fail for umbrella charts
  # with strict subchart schemas — that's expected, template test catches it)
  echo "  → helm lint"
  helm lint "$dir" "${extra_values[@]}" --quiet 2>&1 || {
    echo -e "  ⚠ helm lint warnings (expected for umbrella charts with strict subchart schemas)"
  }

  # Helm template dry-run (skip schema validation for strict subcharts)
  echo "  → helm template --dry-run"
  if ! helm template "$dir" --skip-schema-validation "${extra_values[@]}" --debug > /dev/null 2>&1; then
    echo -e "${RED}  ✗ helm template failed (see above)${RESET}"
    helm template "$dir" --skip-schema-validation "${extra_values[@]}" 2>&1 | tail -20
    exit 1
  fi

  # Clean up .tgz artifacts generated by helm dependency update
  find "$dir/charts" -name "*.tgz" -delete 2>/dev/null || true
  find "$dir" -maxdepth 1 -name "*.tgz" -delete 2>/dev/null || true

  echo -e "${GREEN}  ✓ ${chart_name} passes${RESET}"
done

echo ""
echo -e "${GREEN}✓ All ${#helm_dirs[@]} chart(s) validated${RESET}"
