# Source: https://artifacthub.io/packages/helm/bitnami/mongodb
mongodb:
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Auth Configuration                                                        │
  # └─────────────────────────────────────────────────────────────────────────────┘
  auth:
    enabled: true
    username:
    password:
    databases:
      - tapir
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Storage Configuration                                                     │
  # └─────────────────────────────────────────────────────────────────────────────┘
  persistence:
    enabled: true
    storageClass: "csi-hostpath-sc"
    size: "10Gi"
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Resource Configuration                                                    │
  # └─────────────────────────────────────────────────────────────────────────────┘
  resources:
    requests:
      cpu: "256m"
      memory: "512Mi"
