# Source: https://artifacthub.io/packages/helm/bitnami/mongodb
mongodb:
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Storage Configuration                                                     │
  # └─────────────────────────────────────────────────────────────────────────────┘
  persistence:
    enabled: true
    storageClass:
    size: "10Gi"
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Resource Configuration                                                    │
  # └─────────────────────────────────────────────────────────────────────────────┘
  resources:
    requests:
      cpu: "256m"
      memory: "512Mi"
