apiVersion: v2
name: generic-device-plugin
description: Exposes /dev/dri (virtio-gpu) as a schedulable K8s resource via gabe565/generic-device-plugin
type: application
version: 0.2.0
appVersion: latest
dependencies:
  - name: generic-device-plugin
    version: 0.1.3
    repository: https://charts.gabe565.com
