# Global Values - passed in via DevOps repo (Terraform)
repoUrl: ""
path: ""
targetRevision: ""
region: ""
account: ""
clusterName: ""
clusterEndpoint: ""

# Service Values - passed in via DevOps repo (Terraform)
## codefresh
codefresh:
  enable: false

## External Secrets Operator
externalSecrets:
  enable: true
  serviceAccountName:

## jenkins Values
jenkins:
  enable: false

## kubecost Values
kubecost:
  enable: true

## Kube Prometheus Stack
kubePrometheusStack:
  enable: true

## Redis Operator Values
redisOperator:
  enable: false
  environment:
    - production
    - staging
