apiVersion: v2
name: istio
description: Istio umbrella chart — base CRDs, control plane, ingress gateway, and config (Gateway, ClusterIssuer, Certificate, VirtualServices)
type: application
version: 0.1.0
appVersion: "1.25.2"

dependencies:
  - name: base
    version: 1.25.2
    repository: https://istio-release.storage.googleapis.com/charts

  - name: istiod
    version: 1.25.2
    repository: https://istio-release.storage.googleapis.com/charts

  - name: gateway
    alias: ingress-gateway
    version: 1.28.0
    repository: https://istio-release.storage.googleapis.com/charts
