apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prod-notes-app-vars
  namespace: prod-notes-app
spec:
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth
  target:
    name: prod-notes-app-vars
    deletionPolicy: Merge
  dataFrom:
    - find:
        name:
          regexp: .*
