apiVersion: v1
kind: Service
metadata:
  name: {{ include "opendesign.fullname" . }}
  labels: {{- include "opendesign.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: {{ if .Values.enable_auth_proxy }}http-proxy{{ else }}http{{ end }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "opendesign.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
