apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "mongodb.fullname" . }}-ext
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-{{ .Values.dopplerConfig | replace "_" "-" }}
  refreshInterval: 1m
  target:
    name: {{ include "mongodb.fullname" . }}
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: ".*"
