apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels: {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | quote }}
  database: {{ .Values.auth.database | quote }}
