apiVersion: v2
name: opencost
description: A Helm chart for OpenCost (open-source KubeCost)

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# The chart version
version: 2.5.20

# Application version
appVersion: 1.120.2

maintainers:
  - name: local

dependencies:
  - name: opencost
    version: 2.5.20
    repository: https://opencost.github.io/opencost-helm-chart
