# upstream: https://github.com/opencost/opencost-helm-chart
opencost:
  clusterName: "cluster.local"
  opencost:
    prometheus:
      namespace: kube-prometheus-stack
      port: 9090
      labels:
        app.kubernetes.io/name: prometheus
      internal:
        enabled: true
        serviceName: kube-prometheus-stack-prometheus
        namespaceName: kube-prometheus-stack
        port: 9090
        scheme: http
    exporter:
      defaultClusterId: ""
      resources:
        requests:
          cpu: 10m
          memory: 55Mi
      extraEnv:
        LOG_LEVEL: warn
        EMIT_KSM_V1_METRICS: "false"
        EMIT_KSM_V1_METRICS_ONLY: "true"
    metrics:
      kubeStateMetrics:
        emitKsmV1MetricsOnly: true
      serviceMonitor:
        enabled: false
    ui:
      enabled: true
    nodeSelector:
      intent: apps
