apiVersion: v2
name: db-operator
description: A Helm chart for the cloudnative-pg - a PostgreSQL operator
type: application

version: 1.18.6
appVersion: "1.18.6"

dependencies:
  - name: stackgres-operator
    version: 1.18.6
    repository: https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/
