# Docs: https://github.com/db-operator/charts/tree/main/charts/db-operator
# Docs: https://stackgres.io/doc/latest/install/helm/parameters
stackgresOperator:
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Web Console Configuration                                                 │
  # └─────────────────────────────────────────────────────────────────────────────┘
  adminui:
    service:
      exposeHTTP: false
      type: ClusterIP
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Certificate Configuration                                                 │
  # └─────────────────────────────────────────────────────────────────────────────┘
  cert:
    autoapprove: true
    createForOperator: true
    createForWebApi: true
    createForCollector: true
    regenerateCert: true
    certDuration: 730
    regenerateWebCert: true
    regenerateWebRsa: true
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   RBAC Configuration                                                        │
  # └─────────────────────────────────────────────────────────────────────────────┘
  rbac:
    create: true
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Authentication Configuration                                              │
  # └─────────────────────────────────────────────────────────────────────────────┘
  authentication:
    type: jwt
    createAdminSecret: true
    user:
    password:
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Grafana Integration                                                       │
  # └─────────────────────────────────────────────────────────────────────────────┘
  grafana:
    autoEmbed: true
    schema: http
    user:
    password:
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Extensions Configuration                                                  │
  # └─────────────────────────────────────────────────────────────────────────────┘
  extensions:
    repositoryUrls:
      - https://extensions.stackgres.io/postgres/repository
    cache:
      enabled: true
      preloadedExtensions:
        - x86_64/linux/timescaledb-1\.7\.4-pg12
      persistentVolume:
        size: 1Gi
        accessModes:
        - ReadWriteOnce
        storageClass: standard

  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Backup Storage Configuration                                             │
  # └─────────────────────────────────────────────────────────────────────────────┘
  backupStorage:
    enabled: false

  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Cluster Configuration - via clusters.yaml                                 │
  # └─────────────────────────────────────────────────────────────────────────────┘
  clusters:
    environments:
      - name: staging
        storageSize: 1Gi
      - name: production
        storageSize: 2Gi
