stackgres-operator:
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Web Console Configuration                                                 │
  # └─────────────────────────────────────────────────────────────────────────────┘
  adminui:
    service:
      exposeHTTP: false
      type: ClusterIP
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Certificate Configuration                                                 │
  # └─────────────────────────────────────────────────────────────────────────────┘
  cert:
    autoapprove: true
    createForOperator: true
    createForWebApi: true
    createForCollector: true
    regenerateCert: true
    certDuration: 730
    regenerateWebCert: true
    regenerateWebRsa: true
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   RBAC Configuration                                                        │
  # └─────────────────────────────────────────────────────────────────────────────┘
  rbac:
    create: true
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Authentication Configuration                                              │
  # └─────────────────────────────────────────────────────────────────────────────┘
  authentication:
    type: jwt
    createAdminSecret: true
    user: test
    password: test
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Grafana Integration                                                       │
  # └─────────────────────────────────────────────────────────────────────────────┘
  grafana:
    autoEmbed: true
    schema: http
    user:
    password:
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Extensions Configuration                                                  │
  # └─────────────────────────────────────────────────────────────────────────────┘
  extensions:
    repositoryUrls:
      - https://extensions.stackgres.io/postgres/repository
    cache:
      enabled: false
      preloadedExtensions:
        - x86_64/linux/timescaledb-1\.7\.4-pg12
      persistentVolume:
        size: 1Gi

  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Backup Storage Configuration                                             │
  # └─────────────────────────────────────────────────────────────────────────────┘
  backupStorage:
    enabled: False
