apiVersion: stackgres.io/v1
kind: SGPostgresConfig
metadata:
  name: {{ .Values.postgres.configName | default "openagent-pg-config" }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  postgresVersion: {{ .Values.postgres.version | default "18" | quote }}
  postgresql.conf:
    timezone: "America/Chicago"
