# ┌──────────────────────────────────────────────────────────────────────────┐
# │ Custom Values Category: clusters                                         │
# └──────────────────────────────────────────────────────────────────────────┘
# Docs: https://stackgres.io/doc/latest/reference/crd/sgcluster

{{- range $env := .Values.stackgresOperator.clusters.environments }}
---
apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: {{ $env.name }}-db-cluster
  namespace: db-operator
spec:
  instances: 1
  postgres:
    version: 'latest'
  pods:
    persistentVolume:
      storageClass: standard
      size: {{ $env.storageSize }}
{{- end }}
