{{- $environments := list "prod" "staging" -}}
{{- range $env := $environments }}
---
apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: {{ $env }}-db-cluster
  namespace: db-operator

spec:
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Postgres Configuration                                                    │
  # └─────────────────────────────────────────────────────────────────────────────┘
  postgres:
    version: "15"
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Autoscaling Configuration                                                 │
  # └─────────────────────────────────────────────────────────────────────────────┘
  autoscaling:
    minInstances: 1
    maxInstances: 4
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Instance Configuration                                                         │
  # |   - Volume Configuration                                                    │
  # │   - Resource Allocation                                                     │
  # │   - Fault-Tolerence Configuration                                           |
  # └─────────────────────────────────────────────────────────────────────────────┘
  pods:
    persistentVolume:
      size: {{ if eq $env "prod" }}5Gi{{ else }}2Gi{{ end }}
    disableConnectionPooling: false
    disableMetricsExporter: false
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: cluster-name
              operator: In
              values:
              - {{ $env }}-db-cluster
          topologyKey: "kubernetes.io/hostname"
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Additional Configurations                                                 │
  # └─────────────────────────────────────────────────────────────────────────────┘
  configurations:
    # ┌───────────────────────────────────────────────────────────────────────────┐
    # │   Backup Configuration                                                    │
    # └───────────────────────────────────────────────────────────────────────────┘
    backups:
    - path: "/{{ $env }}-backups"
      retention: 5
      cronSchedule: "0 0 * * *"
    # ┌───────────────────────────────────────────────────────────────────────────┐
    # │   Connection Pooling Configuration                                        │
    # └───────────────────────────────────────────────────────────────────────────┘
    sgPoolingConfig: |
      connections:
        max: 200
        default: 5
    # ┌───────────────────────────────────────────────────────────────────────────┐
    # │   PostgreSQL Configuration                                                │
    # └───────────────────────────────────────────────────────────────────────────┘
    sgPostgresConfig: |
      postgresql.conf:
        shared_buffers: "4GB"
        work_mem: "32MB"
        maintenance_work_mem: "1GB"
        effective_cache_size: "12GB"
        random_page_cost: "1.1"

{{- end }}
