{{- range $env := .Values.stackgresOperator.clusters.environments }}
---
apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: {{ $env.name }}-db-cluster
  namespace: db-operator
spec:
  profile: testing
  instances: 1
  postgres:
    version: "17"
  autoscaling:
    mode: horizontal
    minInstances: 2
    maxInstances: 6
    horizontal:
      replicasConnectionsUsageTarget: "0.5"
  pods:
    disableConnectionPooling: false
    disableMetricsExporter: false
    persistentVolume:
      storageClass: local-path
      size: {{ $env.storageSize }}
  configurations:
    sgPoolingConfig: |
      connections:
        max: 200
        default: 5
{{- end }}
