# Docs: https://stackgres.io/doc/latest/reference/crd/sgcluster
{{- $environments := list "prod" "staging" -}}
{{- range $env := $environments }}
---
apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: {{ $env }}-db-cluster
  namespace: db-operator

spec:
  ## production-ready pre-existing config
  profile: production
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Postgres Configuration                                                    │
  # └─────────────────────────────────────────────────────────────────────────────┘
  postgres:
    version: "17"
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Autoscaling Configuration                                                 │
  # └─────────────────────────────────────────────────────────────────────────────┘
  autoscaling:
    mode: horizontal
    minInstances: 2
    maxInstances: 6
    horizontal:
      replicasConnectionsUsageTarget: "0.5"
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Instance Configuration                                                         │
  # |   - Volume Configuration                                                    │
  # │   - Resource Allocation                                                     │
  # │   - Fault-Tolerence Configuration                                           |
  # └─────────────────────────────────────────────────────────────────────────────┘
  pods:
    persistentVolume:
      storageClass: standard
      size: {{ if eq $env "prod" }}5Gi{{ else }}2Gi{{ end }}
    # disableConnectionPooling: false
    disableMetricsExporter: false
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Additional Configurations                                                 │
  # └─────────────────────────────────────────────────────────────────────────────┘
  configurations:
    # ┌───────────────────────────────────────────────────────────────────────────┐
    # │   Backup Configuration                                                    │
    # └───────────────────────────────────────────────────────────────────────────┘
    # backups:
    # - path: "/{{ $env }}-backups"
    #   sgObjectStorage: "db-backup-storage"
    #   retention: 5
    #   cronSchedule: "0 0 * * *"
    # ┌───────────────────────────────────────────────────────────────────────────┐
    # │   Connection Pooling Configuration                                        │
    # └───────────────────────────────────────────────────────────────────────────┘
    # sgPoolingConfig: |
    #   connections:
    #     max: 200
    #     default: 5

{{- end }}
