apiVersion: v2
name: codefresh
description: A Helm chart for the codefresh cicd
type: application

version: 2.6.7
appVersion: "2.6.0"

dependencies:
  - name: codefresh
    version: 2.6.7
    repository: oci://quay.io/codefresh/codefresh
