# -- Doppler config; set by ArgoCD appset. Creates ExternalSecret when present.
dopplerConfig: ""

# -- Storage class for PVCs
storageClass: "local-path"

# -- Cluster domain for ingress
clusterDomain: "maklab.net"
