apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.userServiceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/instance: {{ .Release.Name }}
