{{- if and .Values.database.enabled .Values.dopplerConfig }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kagent-pg
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-{{ .Values.dopplerConfig | replace "_" "-" }}
  refreshInterval: 1m
  target:
    name: kagent-pg
    creationPolicy: Merge
  data:
    - secretKey: superuser-password
      remoteRef:
        key: KAGENT_PG_PASSWORD
{{- end }}
