{{- if .Values.database.enabled }}
{{- $sharedConfig := "svc_stackgres" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kagent-pg-stackgres
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-{{ $sharedConfig | replace "_" "-" }}
  refreshInterval: 1m
  target:
    name: kagent-pg-app
    creationPolicy: Owner
  data:
    - secretKey: superuser-password
      remoteRef:
        key: KAGENT_PG_PASSWORD
    - secretKey: superuser-username
      remoteRef:
        key: KAGENT_PG_SUPERUSER
    - secretKey: database-url
      remoteRef:
        key: KAGENT_PG_URL
{{- end }}
