{{- if .Values.database.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kagent-pg-stackgres
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: SecretStore
    name: kagent-pg
  refreshInterval: 1m
  target:
    name: kagent-pg-app
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        superuser-username: '{{ "{{ .username }}" }}'
        superuser-password: '{{ "{{ .password }}" }}'
        database-url: 'postgres://{{ "{{ .username }}" }}:{{ "{{ .password }}" }}@kagent-pg.{{ .Release.Namespace }}.svc.cluster.local:5432/kagent?sslmode=disable'
  data:
    - secretKey: username
      remoteRef:
        key: PATRONI_SUPERUSER_USERNAME
    - secretKey: password
      remoteRef:
        key: PATRONI_SUPERUSER_PASSWORD
{{- end }}
