{{- if .Values.database.enabled }}
apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: kagent-pg
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 1
  postgres:
    version: {{ .Values.database.pgVersion | quote }}
  profile: {{ .Values.database.profile | quote }}
  pods:
    persistentVolume:
      size: {{ .Values.database.storage }}
      {{- if .Values.storageClass }}
      storageClass: {{ .Values.storageClass }}
      {{- end }}
    disableMetricsExporter: true
    disablePostgresUtil: false
  configurations:
    sgPostgresConfig: "kagent-pg-config"
    sgPoolingConfig: "kagent-pg-pooling"
{{- end }}
