{{- if .Values.database.enabled }}
apiVersion: stackgres.io/v1
kind: SGScript
metadata:
  name: kagent-pg-init-db
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  continueOnError: false
  scripts:
    - name: create-kagent-database
      database: postgres
      retryOnError: true
      script: |
        CREATE DATABASE kagent;
{{- end }}