apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onedev-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-{{ .Values.dopplerConfig | replace "_" "-" }}
  refreshInterval: 24h
  target:
    name: onedev-secrets
    creationPolicy: Merge
  data:
    - secretKey: dbPassword
      remoteRef:
        key: DB_PASSWORD
