apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onedev-db-creds
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-{{ .Values.dopplerConfig | replace "_" "-" }}
  refreshInterval: 1m
  target:
    name: onedev-db-creds
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: ".*"
