apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onedev-pg-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-{{ .Values.dopplerConfig | replace "_" "-" }}
  refreshInterval: 1m
  target:
    name: onedev-pg-credentials
    creationPolicy: Owner
  data:
    - secretKey: dbUser
      remoteRef:
        key: DB_USER
    - secretKey: dbPassword
      remoteRef:
        key: DB_PASSWORD
