apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: {{ .Values.postgresql.clusterName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  instances: {{ .Values.postgresql.instances }}
  postgres:
    version: {{ .Values.postgresql.postgresVersion | default "latest" | quote }}
  profile: {{ .Values.postgresql.profile | quote }}
  {{- if .Values.postgresql.sgInstanceProfile }}
  sgInstanceProfile: {{ .Values.postgresql.sgInstanceProfile | quote }}
  {{- end }}
  pods:
    persistentVolume:
      size: {{ .Values.postgresql.storage }}
      {{- if .Values.storageClass }}
      storageClass: {{ .Values.storageClass }}
      {{- end }}
    disableMetricsExporter: true
    disableConnectionPooling: true
    disablePostgresUtil: false
  {{- if or .Values.postgresql.sgPostgresConfig .Values.postgresql.sgPoolingConfig }}
  configurations:
    {{- if .Values.postgresql.sgPostgresConfig }}
    sgPostgresConfig: {{ .Values.postgresql.sgPostgresConfig | quote }}
    {{- end }}
    {{- if .Values.postgresql.sgPoolingConfig }}
    sgPoolingConfig: {{ .Values.postgresql.sgPoolingConfig | quote }}
    {{- end }}
  {{- end }}
