headlamp:
  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   General Configuration                                                     │
  # └─────────────────────────────────────────────────────────────────────────────┘
  config:
    pluginsDir: /build/plugins
  serviceAccount:
    create: true
    name: headlamp-admin-sa
  clusterRoleBinding:
    create: true
    name: cluster-admin

  # ┌─────────────────────────────────────────────────────────────────────────────┐
  # │   Headlamp Plugins Configuration                                            │
  # └─────────────────────────────────────────────────────────────────────────────┘
  initContainers:
    - command:
        - /bin/sh
        - -c
        - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
      image: quay.io/kubescape/headlamp-plugin:latest
      name: kubescape-plugin
      volumeMounts:
        - mountPath: /build/plugins
          name: headlamp-plugins
  volumeMounts:
    - name: headlamp-plugins
      mountPath: /build/plugins
  volumes:
    - name: headlamp-plugins
      emptyDir: {}
