apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-svc-tailscale
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: TAILSCALE_OAUTH_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: TAILSCALE_OAUTH_CLIENT_SECRET
