{{- if and .Values.ghcrPullSecret .Values.dopplerConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.ghcrPullSecret | quote }}
{{- end }}
