{{- if .Values.litellm.enabled }}
{{- if .Values.litellm.masterkeySecretName }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.litellm.masterkeySecretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-{{ .Values.dopplerConfig | replace "_" "-" }}
  refreshInterval: 24h
  target:
    name: {{ .Values.litellm.masterkeySecretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.litellm.masterkeySecretKey | default "masterkey" }}
      remoteRef:
        key: LITELLM_MASTER_KEY
{{- end }}
{{- end }}
