apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "litellm.fullname" . }}-pg
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  secretStoreRef:
    kind: SecretStore
    name: kagent-pg
  refreshInterval: 24h
  target:
    name: litellm-pg
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        database-url: 'postgres://{{ "{{ .username }}" }}:{{ "{{ .password }}" }}@kagent-pg.{{ .Release.Namespace }}.svc.cluster.local:5432/litellm?sslmode=disable'
  data:
    - secretKey: username
      remoteRef:
        key: kagent-pg
        property: PATRONI_SUPERUSER_USERNAME
    - secretKey: password
      remoteRef:
        key: kagent-pg
        property: PATRONI_SUPERUSER_PASSWORD
