apiVersion: v1
kind: Service
metadata:
  name: {{ include "litellm.fullname" . }}
  labels:
    {{- include "litellm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: proxy
      protocol: TCP
      name: proxy
  selector:
    {{- include "litellm.labels" . | nindent 4 }}
