##########################
# CONTROL APP COMPONENTS #
##########################
apps: &app_values
  backend:
    port: 8080
    replicas: 1
    resourceRequests:
      cpu: 100m
      memory: 256Mi
    image: ghcr.io/jomakori/note-app-backend
  frontend:
    port: 8181
    replicas: 1
    resourceRequests:
      cpu: 150m
      memory: 256Mi
    image: ghcr.io/jomakori/note-app-frontend
############################
# CONTROL APP ENVIRONMENTS #
############################
environments:
  # staging name is passed from argocd-appset
  - name: ""
    apiHost: "staging.api.notes.net"
    uiHost: "staging.notes.net"
    dopplerToken: ""
    tag: "pr-3"
    <<: *app_values
  # prod name is passed from argocd-appset
  - name: ""
    apiHost: "api.notes.net"
    uiHost: "notes.net"
    dopplerToken: ""
    tag: "1.0.0"
    <<: *app_values
