{{- range $config, $opts := .Values.clusterSecretStores }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: doppler-{{ $config | replace "_" "-" }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    doppler:
      project: {{ $opts.project }}
      config: {{ $opts.config }}
      auth:
        secretRef:
          dopplerToken:
            name: doppler-machine-token
            key: dopplerToken
            namespace: default
{{- end }}
