apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tapir.fullname" . }}
  labels:
    {{- include "tapir.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.persistence.annotations | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "5Gi" }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
