{{- if and (.Values.cloudnativePG) (.Values.cloudnativePG.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloudnative-db-operator
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: staging
            namespace: staging-db
          - env: prod
            namespace: prod-db
  template:
    metadata:
      name: cloudnative-db-operator-{{ .Values.env }}
    spec:
      project: default
      source:
        repoURL: "{{ .Values.repoUrl }}"
        path: services/helm/cloudnative-pg
        targetRevision: "{{ .Values.targetRevision }}"
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'db-{{ .Values.env }}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
          - Replace=true
{{- end }}
