{{- if and (.Values.cloudnativePG) (.Values.cloudnativePG.enable) -}}
{{- range .Values.cloudnativePG.env }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-db-operator-{{ . }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "{{ $.Values.repoUrl }}"
    path: services/helm/cloudnative-pg
    targetRevision: "{{ $.Values.targetRevision }}"
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: cloudnative-pg.extraDeploy[0].stringData.username
          value: "{{ $.Values.cloudnativePG.creds.user }}"
        - name: cloudnative-pg.extraDeploy[0].stringData.password
          value: "{{ $.Values.cloudnativePG.creds.pw }}"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cnpg-db-{{ . }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
---
{{- end }}
{{- end -}}
