{{- if and (.Values.dbOperator) (.Values.dbOperator.enable) -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db-operator
  namespace: argocd
  annotations:
  argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: "{{ $.Values.repoUrl }}"
    path: services/helm/db-operator
    targetRevision: "{{ $.Values.targetRevision }}"
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: stackgres-operator.authentication.user
          value: "{{ $.Values.dbOperator.creds.user }}"
        - name: stackgres-operator.authentication.password
          value: "{{ $.Values.dbOperator.creds.pw }}"
        - name: stackgres-operator.grafana.user
          value: "{{ $.Values.grafanaCreds.admin }}"
        - name: stackgres-operator.grafana.password
          value: "{{ $.Values.grafanaCreds.pw }}"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: db-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end }}
