{{- if and (.Values.devtron) (.Values.devtron.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devtron
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  revisionHistoryLimit: 3
  source:
    repoURL: "{{ .Values.repoUrl }}"
    path: services/helm/devtron
    targetRevision: "{{ .Values.targetRevision }}"
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: devtroncd    # Note: requirement of this deployment
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
