{{- if .Values.kagentUpstream.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-crds
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: oci://ghcr.io/kagent-dev/kagent/helm/kagent-crds
    targetRevision: 0.9.10
    path: "."
    helm:
      releaseName: kagent-crds
  destination:
    server: {{ .Values.clusterServer | default "https://kubernetes.default.svc" }}
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{- end }}