{{- if and (.Values.keda) (.Values.keda.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  revisionHistoryLimit: 3
  source:
    repoURL: "{{ .Values.repoUrl }}"
    path: services/helm/keda
    targetRevision: "{{ .Values.targetRevision }}"
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end }}
