{{- if and (.Values.mongodb) (.Values.mongodb.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: "{{ $.Values.repoUrl }}"
    path: services/helm/mongodb
    targetRevision: "{{ $.Values.targetRevision }}"
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: auth.username
          value: "{{ $.Values.mongoDBCreds.user }}"
        - name: auth.password
          value: "{{ $.Values.mongoDBCreds.pw }}"
        - name: auth.database
          value: "{{ $.Values.mongoDBCreds.user }}"
        - name: persistence.storageClass
          value: "{{ $.Values.storageClass }}"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mongodb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end }}
