{{- if and (.Values.mongodb) (.Values.mongodb.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "{{ $.Values.repoUrl }}"
    path: services/helm/mongodb
    targetRevision: "{{ $.Values.targetRevision }}"
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: mongodb.auth.host
          value: "{{ $.Values.mongoDBCreds.host }}"
        - name: mongodb.auth.usernames
          value: {{ toJson (splitList "," $.Values.mongoDBCreds.user | toStrings) }}
        - name: mongodb.auth.passwords
          value: {{ toJson (splitList "," $.Values.mongoDBCreds.pw | toStrings) }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mongodb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - ServerSideApply=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end }}
