apiVersion: stackgres.io/v1
kind: SGPoolingConfig
metadata:
  name: {{ .Values.postgres.poolingConfigName | default "openagent-pg-pooling" }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  pgBouncer:
    pgbouncer.ini:
      pgbouncer:
        pool_mode: transaction
        max_client_conn: "100"
