apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgecrab-data
  labels:
    app.kubernetes.io/name: edgecrab
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- with .Values.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
