apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: google-gemini-3-5-flash
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
spec:
  model: google/gemini-3.5-flash
  provider: OpenAI
  baseUrl: {{ .Values.headroom.url }}
  apiKeySecret: kagent-secrets
  apiKeySecretKey: OPENAI_API_KEY
