apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: opencode-north-mini-code-free
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
spec:
  model: opencode/north-mini-code-free
  provider: OpenAI
  baseUrl: {{ .Values.headroom.url }}
  apiKeySecret: kagent-secrets
  apiKeySecretKey: OPENAI_API_KEY
