apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: opencode-deepseek-v4-flash-free
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
spec:
  model: opencode/deepseek-v4-flash-free
  provider: OpenAI
  openAI:
    baseUrl: {{ .Values.headroom.url }}
  apiKeySecret: kagent-secrets
  apiKeySecretKey: OPENAI_API_KEY
