apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-{{ .Values.dopplerConfig | replace "_" "-" }}
  refreshInterval: 1m
  target:
    name: grafana-admin-credentials
  data:
    - secretKey: ADMIN_USER
      remoteRef:
        key: GRAFANA_ADMIN
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: GRAFANA_PW
