# Create envs/namespaces for notes-app
{{- if .Values.notesApp.enabled }}
{{- range $env := .Values.notesApp.environment }}
---
apiVersion: v1
kind: Namespace
metadata:
    name: {{ $env.namespace }}
{{- end }}
{{- end }}
