# Create envs/namespaces for apps
{{- range $key, $cfg := .Values.apps }}
{{- if $cfg.enable }}
{{- $appEnv := index $.Values $key }}
{{- range $envName, $env := $appEnv.environment }}
---
apiVersion: v1
kind: Namespace
metadata:
    name: {{ $env.namespace }}
{{- end }}
{{- end }}
{{- end }}
