# Create envs/namespaces for apps
# Namespace derived from app key (kebab) + env name
{{- range $key, $cfg := .Values.apps }}
{{- if $cfg.enable }}
{{- $kebabKey := include "kebab" $key }}
{{- range $envName, $env := (index $.Values $key).environment }}
---
apiVersion: v1
kind: Namespace
metadata:
    name: {{ $kebabKey }}-{{ $envName }}
{{- end }}
{{- end }}
{{- end }}
