apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-secrets
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-svc-{{ required "dopplerConfig is required (appset injects it)" .Values.dopplerConfig | replace "_" "-" }}
  target:
    name: pg-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: ".*"
