apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-auth-ext
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-{{ .Values.dopplerConfig | replace "_" "-" }}
  refreshInterval: 24h
  target:
    name: cloudflare-tunnel-auth
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: ".*"
