name: Agent - Lint/Test - ${{ github.event_name == 'pull_request' && format('PR-#{0}', github.event.number) || 'On-demand' }}

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'services/helm/kagent/**'
      - 'services/helm/kagent-discord/**'
      - 'services/helm/kagent-headroom/**'
      - 'services/helm/kagent-substrate/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/helm/kagent/tests
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.22'
          cache: true

      - name: Setup Doppler CLI
        uses: dopplerhq/cli-action@master

      - name: Fetch Doppler Secrets
        id: doppler
        uses: dopplerhq/secrets-fetch-action@main
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          inject-env-vars: true

      - name: Lint
        working-directory: services/helm/kagent/tests
        run: |
          go vet ./...

      - name: Run unit tests
        working-directory: services/helm/kagent/tests
        run: |
          make tests

      - name: Run integration tests
        working-directory: services/helm/kagent/tests
        run: make full_coverage
