name: Lint and Test Charts

on:
  workflow_dispatch:  # manual run option
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
          check-latest: true

      - name: Setup Chart-Testing
        uses: helm/chart-testing-action@v2

      - name: Setup Doppler CLI
        uses: dopplerhq/cli-action@master

      - name: Fetch Doppler Secrets
        id: doppler
        uses: dopplerhq/secrets-fetch-action@main
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          inject-env-vars: true

      - name: Grab File changes
        id: changed-files
        uses: tj-actions/changed-files@main

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GOOGLE_CI_CREDENTIALS }}

      - name: Authenticate GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_LOCATION }}
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: CT - Helm Chart Lint & Test
        env:
          changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          # Confirm k8s setup and connection
          cluster_config=$(kubectl config current-context 2>&1)
          cluster_connection=$(kubectl cluster-info 2>&1)

          # Test Helm charts - if no errors
          if [ -z "$cluster_config" ]; then
              echo "::error::$cluster_config"
              exit 1
          elif [-z "$cluster_connection" ]; then
              echo "::error::$cluster_connection"
              exit 1
          else
              echo "Testing out changes on: $cluster_config" && ./ct_check.sh "$changed_files"
          fi
